FROM python:3.10-slim

WORKDIR / app

COPY . .

COPY requirements_backend.txt .

RUN pip install --no-cache-dir -r requirements_backend.txt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]